### ISSUE TITLE
Define return message

### ISSUE THREAD

**Issue by david4096** [Kusdhill/researchingRegions#6]
Talk about the alternative and reasoning for using this one somewhere in the code. It should be easy to implement either a denormalized or n

```
   gene:
        feature: GA feature message
   matches:
        variant: GA variant message
        annotation: GA annotation message
        biosample: GA biosample message
```
